# When in need, check documentation https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow

name: Package and release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      #CF_API_KEY: ${{ secrets.CF_API_KEY }}
      #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      # we first have to clone the AddOn project, this is a required step
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for changelog

      # once cloned, we just run the GitHub Action for the packager project
      - name: Package and release
        uses: BigWigsMods/packager@v2

      # another example where we supply additional arguments, this example is specifically to release
      # for the Wrath of the Lich King Classic version of the game and doesn't upload to WoWInterface
      - name: Package and release for Wrath of the Lich King Classic
        uses: BigWigsMods/packager@v2
        with:
          args: -g wrath -w 0